import { Inter, Roboto } from "next/font/google";
import "./globals.css";

import "swiper/css";
import "swiper/css/pagination";
import "swiper/css/navigation";
import { Suspense } from "react";
import { AppContainer } from "@/components/structure/Providers";
import AccountModal from "@/components/modals/AccountModal/AccountModal";
import { Bounce, ToastContainer } from "react-toastify";

const inter = Inter({
  subsets: ["latin"],
  variable: "--font-inter",
  weight: ["100", "200", "300", "400", "500", "600", "700", "800", "900"],
});

const roboto = Roboto({
  subsets: ["latin"],
  variable: "--font-roboto",
  weight: ["100", "200", "300", "400", "500", "600", "700", "800", "900"],
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={`${inter.variable} ${roboto.variable}`}>
        <Suspense>
          <AppContainer>
            <AccountModal />
            {children}
          </AppContainer>
          <ToastContainer
            position="top-right"
            autoClose={5000}
            hideProgressBar={false}
            newestOnTop={false}
            closeOnClick
            rtl={false}
            pauseOnFocusLoss
            draggable
            pauseOnHover
            theme="light"
            transition={Bounce}
            style={{ zIndex: 10000000 }}
          />
        </Suspense>
      </body>
    </html>
  );
}
