const terms = [
  "Income",
  "Expense",
  "Budget",
  "Savings",
  "Emergency Fund",
  "Net Worth",
  "Assets",
  "Liabilities",
  "Checking Account",
  "Savings Account",
  "Interest Rate",
  "Compound Interest",
  "Credit Score",
  "Credit Report",
  "Credit Card",
  "Debit Card",
  "Credit Limit",
  "APR (Annual Percentage Rate)",
  "Auto Loan",
  "Mortgage",
  "Home Equity",
  "Refinancing",
  "Student Loan",
  "Debt Consolidation",
  "Debt-to-Income Ratio",
  "Minimum Payment",
  "Overdraft",
  "Bankruptcy",
  "Cash Flow",
  "Discretionary Spending",
  "Fixed Expense",
  "Variable Expense",
  "Recurring Expense",
  "Direct Deposit",
  "Paycheck",
  "Gross Income",
  "Net Income",
  "Withholding",
  "Tax Bracket",
  "Tax Deduction",
  "Tax Credit",
  "W-2 Form",
  "1099 Form",
  "IRA (Individual Retirement Account)",
  "Roth IRA",
  "401(k)",
  "Roth 401(k)",
  "Pension",
  "Social Security",
  "Retirement Savings",
  "Health Savings Account (HSA)",
  "Flexible Spending Account (FSA)",
  "Investment",
  "Stock",
  "Bond",
  "Mutual Fund",
  "ETF (Exchange-Traded Fund)",
  "Robo-advisor",
  "Brokerage Account",
  "Diversification",
  "Risk Tolerance",
  "Portfolio",
  "Capital Gain",
  "Capital Loss",
  "Real Estate Investment",
  "Rental Income",
  "Annuity",
  "Insurance",
  "Life Insurance",
  "Term Life Insurance",
  "Whole Life Insurance",
  "Disability Insurance",
  "Auto Insurance",
  "Homeowners Insurance",
  "Renter’s Insurance",
  "Premium",
  "Deductible",
  "Co-pay",
  "Beneficiary",
  "Estate Planning",
  "Will",
  "Trust",
  "Power of Attorney",
  "Inheritance",
  "Financial Goal",
  "Short-term Goal",
  "Long-term Goal",
  "Financial Plan",
  "Financial Advisor",
  "Expense Tracking",
  "Impulse Purchase",
  "Frugality",
  "Couponing",
  "Cashback",
  "Rewards Program",
  "Side Hustle",
  "Passive Income",
  "Net Pay",
  "Inflation",
  "Cost of Living"
]

export default terms